# Generated by Django 2.2.6 on 2019-12-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='nome')),
            ],
            options={
                'db_table': 'foto',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='dislikes'),
        ),
        migrations.AddField(
            model_name='produto',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
    ]
