# Generated by Django 2.2.6 on 2019-12-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_auto_20191211_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(max_length=120),
        ),
    ]
